#!/bin/bash
offset=30+30
wmctrl -T master$$ -r :ACTIVE:
wmctrl -c 'counter 15'
xterm +fullscreen -geometry 2x1+$offset -fa 'Monospace' -fs 35 -e '/home/thomas/Streaming/DBD/scripts/counter 15' & sleep 0.25
wmctrl -r 'counter 15' -b add,above
wmctrl -a master$$
