#!/bin/bash
offset=30+120
wmctrl -T master$$ -r :ACTIVE:
wmctrl -c 'counter 60'
xterm +fullscreen -geometry 2x1+$offset -fa 'Monospace' -fs 35 -e '/home/thomas/Streaming/DBD/scripts/counter 60' & sleep 0.25
wmctrl -r 'counter 60' -b add,above
wmctrl -a master$$
